[registers]
   R1=16 # unclear if these values are int or hex
   R3=42
   R5=8

[memory]
   8 = 40 # unclear if these values are int or hex
   16 = 60

[code]
   code = """
         LD R2, 0(R1)
         DADD R4, R2, R3
         SD R4, 0(R1)
         BNEZ R4, NEXT
         DADD R2, R1, #8
   NEXT: DADD R1, R1, R3
   """
